name: Deploy via SSH

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 2000 -H 127.0.0.1 >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh -p 2000 parallels@127.0.0.1 "mkdir -p ~/app"
          scp -P 2000 -r . parallels@127.0.0.1:~/app/
