name: Deploy to VM via SSH

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_USER: parallels
      DEPLOY_HOST: 10.211.55.6      # <-- Replace with your VM's public IP or DNS
      DEPLOY_PORT: 2222
      DEPLOY_PATH: ~/CLI_TOOL               # <-- Remote path to deploy to

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p $DEPLOY_PORT -H $DEPLOY_HOST >> ~/.ssh/known_hosts

      - name: Deploy code to VM
        run: |
          ssh -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST "mkdir -p $DEPLOY_PATH"
          scp -P $DEPLOY_PORT -r . $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/
